### ISSUE TITLE
Question: Use of ieturk within other crowdsourcing platforms

### ISSUE THREAD

**Issue by HiddeTammo** [Varal7/ieturk#3]
This text annotation tool is great and quite straightfoward to setup within Amazon Mechanical Turk. I am working on a research project where the use of a text annotation tool within the field of crowdsourcing can be used such that non-experts are able to label text from medical data. 

Is the use of this software limited to only Amazon Mechanical Turk or can it be used in other crowdsourcing platforms? Of course some changes may need to be made when using the code on other platform but is this code disallowed from being used in other platforms such as figure eight?

**Comment by Varal7** [comment]
This tool is provided under the [MIT license](https://github.com/Varal7/ieturk/blob/master/LICENSE.md)
